# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  workflow_dispatch:
  schedule:
  - cron: '18 1 * * *'
  

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 14
        stale-issue-message: 'Due to inactivity, this issue will be closed in 7 days. Thank you for your contributions.'
        stale-pr-message: 'Due to inactivity, this pull request will be closed in 7 days. Thank you for your contributions.'
