name: Create daily tag

on:
  schedule:
    - cron: "58 23 * * *"

jobs:
  tag:
    name: Create daily tag
    runs-on: ubuntu-latest
    steps:

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"

    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Create tag
      uses: rickstaa/action-create-tag@v1
      with:
        tag: log4shell_info_${{ steps.date.outputs.date }}
        message: Log4shell info ${{ steps.date.outputs.date }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'

    - run: pip install -r ${{ github.workspace }}/tools/log4shell_softwarelist/requirements.txt

    - run: python ${{ github.workspace }}/tools/log4shell_softwarelist/softwarelist_parser.py --path ${{ github.workspace }}/software/ csv software_list.csv

    - run: python ${{ github.workspace }}/tools/log4shell_softwarelist/softwarelist_parser.py --path ${{ github.workspace }}/software/ json software_list.json

    - uses: softprops/action-gh-release@v1
      with:
          tag_name: log4shell_info_${{ steps.date.outputs.date }}
          files: |
              software_list.csv
              software_list.json
